export default [
  {
    id: 1,
    title: "Life lessons with Katie Zaferes",
    img: "../public/katie-zaferes.png",
    rating: "5.0",
    reviewCount: 10,
    location: "Online",
    cost: "$136",
    openSpots: 0,
  },
  {
    id: 2,
    title: "Learn wedding photography",
    img: "../public/wedding-photography.png",
    rating: "5.0",
    reviewCount: 30,
    location: "USA",
    cost: "$125",
    openSpots: 20,
  },
  {
    id: 3,
    title: "Group Mountain Biking",
    img: "../public/mountain-bike.png",
    rating: "4.8",
    reviewCount: 2,
    location: "Norway",
    cost: "$50",
    openSpots: 6,
  },
];
